// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/BezierCurveProto.proto

// Protobuf Java Version: 3.25.6
package org.kobe.xbot.xdashbackend.utilities;

public final class BezierCurveProto {
  private BezierCurveProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.kobe.xbot.xdashbackend.utilities.Point)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    double getY();
  }
  /**
   * Protobuf type {@code org.kobe.xbot.xdashbackend.utilities.Point}
   */
  public static final class Point extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.kobe.xbot.xdashbackend.utilities.Point)
      PointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Point.newBuilder() to construct.
    private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Point() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Point();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.internal_static_org_kobe_xbot_xdashbackend_utilities_Point_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.internal_static_org_kobe_xbot_xdashbackend_utilities_Point_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.class, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private double x_ = 0D;
    /**
     * <code>double x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private double y_ = 0D;
    /**
     * <code>double y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        output.writeDouble(1, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        output.writeDouble(2, y_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point)) {
        return super.equals(obj);
      }
      org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point other = (org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point) obj;

      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
      if (java.lang.Double.doubleToLongBits(getY())
          != java.lang.Double.doubleToLongBits(
              other.getY())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.kobe.xbot.xdashbackend.utilities.Point}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.kobe.xbot.xdashbackend.utilities.Point)
        org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.internal_static_org_kobe_xbot_xdashbackend_utilities_Point_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.internal_static_org_kobe_xbot_xdashbackend_utilities_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.class, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder.class);
      }

      // Construct using org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        x_ = 0D;
        y_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.internal_static_org_kobe_xbot_xdashbackend_utilities_Point_descriptor;
      }

      @java.lang.Override
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point getDefaultInstanceForType() {
        return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance();
      }

      @java.lang.Override
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point build() {
        org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point buildPartial() {
        org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point result = new org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.y_ = y_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point) {
          return mergeFrom((org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point other) {
        if (other == org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance()) return this;
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                x_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                y_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double x_ ;
      /**
       * <code>double x = 1;</code>
       * @return The x.
       */
      @java.lang.Override
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 1;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {

        x_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 2;</code>
       * @return The y.
       */
      @java.lang.Override
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 2;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {

        y_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.kobe.xbot.xdashbackend.utilities.Point)
    }

    // @@protoc_insertion_point(class_scope:org.kobe.xbot.xdashbackend.utilities.Point)
    private static final org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point();
    }

    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Point>
        PARSER = new com.google.protobuf.AbstractParser<Point>() {
      @java.lang.Override
      public Point parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Point> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Point> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlanBezierPathRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.kobe.xbot.xdashbackend.utilities.PlanBezierPathRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
     * @return Whether the start field is set.
     */
    boolean hasStart();
    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
     * @return The start.
     */
    org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point getStart();
    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
     */
    org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder getStartOrBuilder();

    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
     * @return Whether the goal field is set.
     */
    boolean hasGoal();
    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
     * @return The goal.
     */
    org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point getGoal();
    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
     */
    org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder getGoalOrBuilder();

    /**
     * <code>double safeRadiusInches = 3;</code>
     * @return The safeRadiusInches.
     */
    double getSafeRadiusInches();

    /**
     * <code>double metersPerSecond = 4;</code>
     * @return The metersPerSecond.
     */
    double getMetersPerSecond();
  }
  /**
   * Protobuf type {@code org.kobe.xbot.xdashbackend.utilities.PlanBezierPathRequest}
   */
  public static final class PlanBezierPathRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.kobe.xbot.xdashbackend.utilities.PlanBezierPathRequest)
      PlanBezierPathRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlanBezierPathRequest.newBuilder() to construct.
    private PlanBezierPathRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlanBezierPathRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlanBezierPathRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.internal_static_org_kobe_xbot_xdashbackend_utilities_PlanBezierPathRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.internal_static_org_kobe_xbot_xdashbackend_utilities_PlanBezierPathRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest.class, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest.Builder.class);
    }

    private int bitField0_;
    public static final int START_FIELD_NUMBER = 1;
    private org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point start_;
    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
     * @return Whether the start field is set.
     */
    @java.lang.Override
    public boolean hasStart() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
     * @return The start.
     */
    @java.lang.Override
    public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point getStart() {
      return start_ == null ? org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance() : start_;
    }
    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
     */
    @java.lang.Override
    public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder getStartOrBuilder() {
      return start_ == null ? org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance() : start_;
    }

    public static final int GOAL_FIELD_NUMBER = 2;
    private org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point goal_;
    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
     * @return Whether the goal field is set.
     */
    @java.lang.Override
    public boolean hasGoal() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
     * @return The goal.
     */
    @java.lang.Override
    public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point getGoal() {
      return goal_ == null ? org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance() : goal_;
    }
    /**
     * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
     */
    @java.lang.Override
    public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder getGoalOrBuilder() {
      return goal_ == null ? org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance() : goal_;
    }

    public static final int SAFERADIUSINCHES_FIELD_NUMBER = 3;
    private double safeRadiusInches_ = 0D;
    /**
     * <code>double safeRadiusInches = 3;</code>
     * @return The safeRadiusInches.
     */
    @java.lang.Override
    public double getSafeRadiusInches() {
      return safeRadiusInches_;
    }

    public static final int METERSPERSECOND_FIELD_NUMBER = 4;
    private double metersPerSecond_ = 0D;
    /**
     * <code>double metersPerSecond = 4;</code>
     * @return The metersPerSecond.
     */
    @java.lang.Override
    public double getMetersPerSecond() {
      return metersPerSecond_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getStart());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(2, getGoal());
      }
      if (java.lang.Double.doubleToRawLongBits(safeRadiusInches_) != 0) {
        output.writeDouble(3, safeRadiusInches_);
      }
      if (java.lang.Double.doubleToRawLongBits(metersPerSecond_) != 0) {
        output.writeDouble(4, metersPerSecond_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getStart());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getGoal());
      }
      if (java.lang.Double.doubleToRawLongBits(safeRadiusInches_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, safeRadiusInches_);
      }
      if (java.lang.Double.doubleToRawLongBits(metersPerSecond_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, metersPerSecond_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest)) {
        return super.equals(obj);
      }
      org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest other = (org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest) obj;

      if (hasStart() != other.hasStart()) return false;
      if (hasStart()) {
        if (!getStart()
            .equals(other.getStart())) return false;
      }
      if (hasGoal() != other.hasGoal()) return false;
      if (hasGoal()) {
        if (!getGoal()
            .equals(other.getGoal())) return false;
      }
      if (java.lang.Double.doubleToLongBits(getSafeRadiusInches())
          != java.lang.Double.doubleToLongBits(
              other.getSafeRadiusInches())) return false;
      if (java.lang.Double.doubleToLongBits(getMetersPerSecond())
          != java.lang.Double.doubleToLongBits(
              other.getMetersPerSecond())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStart()) {
        hash = (37 * hash) + START_FIELD_NUMBER;
        hash = (53 * hash) + getStart().hashCode();
      }
      if (hasGoal()) {
        hash = (37 * hash) + GOAL_FIELD_NUMBER;
        hash = (53 * hash) + getGoal().hashCode();
      }
      hash = (37 * hash) + SAFERADIUSINCHES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getSafeRadiusInches()));
      hash = (37 * hash) + METERSPERSECOND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMetersPerSecond()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.kobe.xbot.xdashbackend.utilities.PlanBezierPathRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.kobe.xbot.xdashbackend.utilities.PlanBezierPathRequest)
        org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.internal_static_org_kobe_xbot_xdashbackend_utilities_PlanBezierPathRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.internal_static_org_kobe_xbot_xdashbackend_utilities_PlanBezierPathRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest.class, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest.Builder.class);
      }

      // Construct using org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStartFieldBuilder();
          getGoalFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        start_ = null;
        if (startBuilder_ != null) {
          startBuilder_.dispose();
          startBuilder_ = null;
        }
        goal_ = null;
        if (goalBuilder_ != null) {
          goalBuilder_.dispose();
          goalBuilder_ = null;
        }
        safeRadiusInches_ = 0D;
        metersPerSecond_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.internal_static_org_kobe_xbot_xdashbackend_utilities_PlanBezierPathRequest_descriptor;
      }

      @java.lang.Override
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest getDefaultInstanceForType() {
        return org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest build() {
        org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest buildPartial() {
        org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest result = new org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.start_ = startBuilder_ == null
              ? start_
              : startBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.goal_ = goalBuilder_ == null
              ? goal_
              : goalBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.safeRadiusInches_ = safeRadiusInches_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.metersPerSecond_ = metersPerSecond_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest) {
          return mergeFrom((org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest other) {
        if (other == org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest.getDefaultInstance()) return this;
        if (other.hasStart()) {
          mergeStart(other.getStart());
        }
        if (other.hasGoal()) {
          mergeGoal(other.getGoal());
        }
        if (other.getSafeRadiusInches() != 0D) {
          setSafeRadiusInches(other.getSafeRadiusInches());
        }
        if (other.getMetersPerSecond() != 0D) {
          setMetersPerSecond(other.getMetersPerSecond());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getStartFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getGoalFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 25: {
                safeRadiusInches_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                metersPerSecond_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point start_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder> startBuilder_;
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
       * @return Whether the start field is set.
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
       * @return The start.
       */
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point getStart() {
        if (startBuilder_ == null) {
          return start_ == null ? org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance() : start_;
        } else {
          return startBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
       */
      public Builder setStart(org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point value) {
        if (startBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          start_ = value;
        } else {
          startBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
       */
      public Builder setStart(
          org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder builderForValue) {
        if (startBuilder_ == null) {
          start_ = builderForValue.build();
        } else {
          startBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
       */
      public Builder mergeStart(org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point value) {
        if (startBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            start_ != null &&
            start_ != org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance()) {
            getStartBuilder().mergeFrom(value);
          } else {
            start_ = value;
          }
        } else {
          startBuilder_.mergeFrom(value);
        }
        if (start_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000001);
        start_ = null;
        if (startBuilder_ != null) {
          startBuilder_.dispose();
          startBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
       */
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder getStartBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getStartFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
       */
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder getStartOrBuilder() {
        if (startBuilder_ != null) {
          return startBuilder_.getMessageOrBuilder();
        } else {
          return start_ == null ?
              org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance() : start_;
        }
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point start = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder> 
          getStartFieldBuilder() {
        if (startBuilder_ == null) {
          startBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder>(
                  getStart(),
                  getParentForChildren(),
                  isClean());
          start_ = null;
        }
        return startBuilder_;
      }

      private org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point goal_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder> goalBuilder_;
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
       * @return Whether the goal field is set.
       */
      public boolean hasGoal() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
       * @return The goal.
       */
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point getGoal() {
        if (goalBuilder_ == null) {
          return goal_ == null ? org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance() : goal_;
        } else {
          return goalBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
       */
      public Builder setGoal(org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point value) {
        if (goalBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          goal_ = value;
        } else {
          goalBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
       */
      public Builder setGoal(
          org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder builderForValue) {
        if (goalBuilder_ == null) {
          goal_ = builderForValue.build();
        } else {
          goalBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
       */
      public Builder mergeGoal(org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point value) {
        if (goalBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            goal_ != null &&
            goal_ != org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance()) {
            getGoalBuilder().mergeFrom(value);
          } else {
            goal_ = value;
          }
        } else {
          goalBuilder_.mergeFrom(value);
        }
        if (goal_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
       */
      public Builder clearGoal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        goal_ = null;
        if (goalBuilder_ != null) {
          goalBuilder_.dispose();
          goalBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
       */
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder getGoalBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getGoalFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
       */
      public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder getGoalOrBuilder() {
        if (goalBuilder_ != null) {
          return goalBuilder_.getMessageOrBuilder();
        } else {
          return goal_ == null ?
              org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.getDefaultInstance() : goal_;
        }
      }
      /**
       * <code>.org.kobe.xbot.xdashbackend.utilities.Point goal = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder> 
          getGoalFieldBuilder() {
        if (goalBuilder_ == null) {
          goalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.Point.Builder, org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PointOrBuilder>(
                  getGoal(),
                  getParentForChildren(),
                  isClean());
          goal_ = null;
        }
        return goalBuilder_;
      }

      private double safeRadiusInches_ ;
      /**
       * <code>double safeRadiusInches = 3;</code>
       * @return The safeRadiusInches.
       */
      @java.lang.Override
      public double getSafeRadiusInches() {
        return safeRadiusInches_;
      }
      /**
       * <code>double safeRadiusInches = 3;</code>
       * @param value The safeRadiusInches to set.
       * @return This builder for chaining.
       */
      public Builder setSafeRadiusInches(double value) {

        safeRadiusInches_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double safeRadiusInches = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSafeRadiusInches() {
        bitField0_ = (bitField0_ & ~0x00000004);
        safeRadiusInches_ = 0D;
        onChanged();
        return this;
      }

      private double metersPerSecond_ ;
      /**
       * <code>double metersPerSecond = 4;</code>
       * @return The metersPerSecond.
       */
      @java.lang.Override
      public double getMetersPerSecond() {
        return metersPerSecond_;
      }
      /**
       * <code>double metersPerSecond = 4;</code>
       * @param value The metersPerSecond to set.
       * @return This builder for chaining.
       */
      public Builder setMetersPerSecond(double value) {

        metersPerSecond_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double metersPerSecond = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMetersPerSecond() {
        bitField0_ = (bitField0_ & ~0x00000008);
        metersPerSecond_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.kobe.xbot.xdashbackend.utilities.PlanBezierPathRequest)
    }

    // @@protoc_insertion_point(class_scope:org.kobe.xbot.xdashbackend.utilities.PlanBezierPathRequest)
    private static final org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest();
    }

    public static org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlanBezierPathRequest>
        PARSER = new com.google.protobuf.AbstractParser<PlanBezierPathRequest>() {
      @java.lang.Override
      public PlanBezierPathRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlanBezierPathRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlanBezierPathRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.kobe.xbot.xdashbackend.utilities.BezierCurveProto.PlanBezierPathRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kobe_xbot_xdashbackend_utilities_Point_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_kobe_xbot_xdashbackend_utilities_Point_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_kobe_xbot_xdashbackend_utilities_PlanBezierPathRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_kobe_xbot_xdashbackend_utilities_PlanBezierPathRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035protos/BezierCurveProto.proto\022$org.kob" +
      "e.xbot.xdashbackend.utilities\"\035\n\005Point\022\t" +
      "\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"\301\001\n\025PlanBezierPathR" +
      "equest\022:\n\005start\030\001 \001(\0132+.org.kobe.xbot.xd" +
      "ashbackend.utilities.Point\0229\n\004goal\030\002 \001(\013" +
      "2+.org.kobe.xbot.xdashbackend.utilities." +
      "Point\022\030\n\020safeRadiusInches\030\003 \001(\001\022\027\n\017meter" +
      "sPerSecond\030\004 \001(\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_kobe_xbot_xdashbackend_utilities_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_kobe_xbot_xdashbackend_utilities_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_kobe_xbot_xdashbackend_utilities_Point_descriptor,
        new java.lang.String[] { "X", "Y", });
    internal_static_org_kobe_xbot_xdashbackend_utilities_PlanBezierPathRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_kobe_xbot_xdashbackend_utilities_PlanBezierPathRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_kobe_xbot_xdashbackend_utilities_PlanBezierPathRequest_descriptor,
        new java.lang.String[] { "Start", "Goal", "SafeRadiusInches", "MetersPerSecond", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
