#Default XDASH Configuration
#Fri Dec 13 17:11:38 PST 2024
wifi.robot=koke1
roboRIO.server=roboRIO-488-FRC.local
servers.user=xbot
servers.connectTimeout=3000
services=notelocalization
project.directory=D\:\\stuff\\IdeaProjects\\xdashbackend\\docker
wifi.internet=Louie
server.password=1234
roboRIO.hostname=roboRIO-488-FRC
servers.password=I<3Robots\!
roboRIO.address=10.4.88.2
roboRIO.username=admin
docker.imagesDirectory=XDASH-DOCKER-IMAGES
servers.retryTimeout=4000
