#Default XDASH Configuration
#Mon Dec 30 19:58:20 PST 2024
wifi.robot=koke1
docker.altBaseImageURL=https\://github.com/Kobeeeef/XDASH/releases/download/v1-docker-images/alt-arm64-base-image.tar
docker.altBaseImageImportTimeout=3000
servers.user=xbot
servers.connectTimeout=3000
services=notelocalization
project.directory=D\:\\stuff\\IdeaProjects\\xdashbackend\\docker
wifi.internet=Louie
server.password=1234
servers.password=I<3Robots\!
roboRIO.username=admin
docker.imagesDirectory=XDASH-DOCKER-IMAGES
servers.retryTimeout=4000
servers.constant=["{\\"hostname\\"\:\\"opirl\\",\\"address\\"\:\\"10.0.0.60\\",\\"username\\"\:\\"pi\\",\\"password\\"\:\\"raspberry\\"}"]
