#Default XDASH Configuration
#Fri Jan 31 11:18:58 PST 2025
wifi.robot=koke1
roboRIO.server=roboRIO-488-FRC.local
docker.altBaseImageImportTimeout=3000
docker.altBaseImageURL=https\://github.com/Kobeeeef/XDASH/releases/download/v1-docker-images/alt-arm64-base-image.tar
servers.user=xbot
servers.connectTimeout=3000
services=
project.directory=/home/xbot/matrix/Alt
docker.compose.file.directory=/home/xbot/matrix/Alt/docker-compose.yml
wifi.internet=koke1
server.password=1234
roboRIO.hostname=roboRIO-488-FRC
servers.password=I<3Robots\!
roboRIO.address=10.4.88.2
roboRIO.username=admin
docker.imagesDirectory=xdash-docker-images
servers.retryTimeout=4000
