    spring.application.name=xdashbackend
    server.port=8080
    spring.mvc.view.suffix=.html
    server.error.whitelabel.enabled=true
    spring.devtools.restart.enabled=false
    server.tomcat.threads.max=200
    server.tomcat.threads.min-spare=30
    server.servlet.session.timeout=0
    # Maximum file size
    spring.servlet.multipart.max-file-size=1000GB
    # Maximum request size
    spring.servlet.multipart.max-request-size=1000GB


